openapi: "3.0.3"

info:
  title: Sample API
  version: "1.0.0"

paths:
  {}

components:
  schemas:
    SampleObj:
      type: object
      properties:
        shop:
          type: object
          properties:
            name: { type: string }
            place: { type: string }
        reviews:
          type: array
          items:
            type: object
            properties:
              score:
                type: integer
                enum: [1, 2, 3, 4, 5]
              comment:
                type: string
