# データ型

openapi: "3.0.3"

info:
  title: "sample"
  version: "1.0.0"

paths:
 {}

components:
 schemas:
   SampleInt32:
     type: integer
     format: int32
   SampleDateStr:
     type: string
     format: date